"""add confidence column to triage_outcomes

Revision ID: 72f9f459f439
Revises: db3d038fbbde
Create Date: 2026-09-12 14:43:35.637360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f9f459f439'
down_revision: Union[str, None] = 'db3d038fbbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triage_outcomes', sa.Column('confidence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triage_outcomes', 'confidence')
    # ### end Alembic commands ###
