"""add specialist_called column to triage_outcomes

Revision ID: c83d2044854c
Revises: 72f9f459f439
Create Date: 2026-09-17 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83d2044854c'
down_revision: Union[str, None] = '72f9f459f439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triage_outcomes', sa.Column('specialist_called', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triage_outcomes', 'specialist_called')
    # ### end Alembic commands ###